<?php
/**
 * Created by PhpStorm.
 * User: new
 * Date: 4/19/2017
 * Time: 11:22 AM
 */

return [
    'unik'                          => 'Unik',
    'invoice_hash'                  => 'Invoice: #',
    'invoice_number'                => 'Invoice_Number_',
    'dated'                         => ' dated ',
    'generated_by'                  => ' has been generated by ',
    'email_template'                => 'email.activation-notification',
    'email_not_found'               => 'User is not found by this email.',
    //'from'                          => 'weare@cyberconsorts.com',
    'from'                          => 'pardeep287@gmail.com',
    'from_title'                    => 'Unik',
    'subject'                       => 'Account Notification',
    'reset_password'                => 'Reset Password',
    'body'                          => 'Your Account has been activated by admin, Please login into your account to verify.',
    'reset_password_message_one'    => 'Your password has been successfully changed, Use ',
    'reset_password_message_second' => 'password to login into your account.',
    'password_changed'              => 'We have sent the password in you email, please check your mail',
    'hello'                         => 'Hello',
    'copyright'                     => '&copy; 2017, All Rights Reserved by cyberconsorts Pty Ltd',
    'sent_from_erp'                 => 'Sent From ERP',
    'order_hash'                    => 'Order: #',
    'powered_by'                    => 'Powered by:',
    'cyberconsorts'                 => 'www.cyberconsorts.com',
    'note'                          => 'Note',
    'quotation_number'              => 'Quotation_Number_',
    'quotation_order'               => 'Quotation has been generated, Please check the attached Quotation.',
    'regards_detail'                => 'Regards <br> cyberconsorts Pty Ltd<br>422/R 2nd Floor, Mall Road, Model Town,<br>
Jalandhar City Punjab (INDIA) <br> Phone: 0181-4658777  <br> ',
    'email_send'					=> ':attribute Email has been sent to customer successfully',
];